version: "3"
services: 
  ansible:
    image: testing/image
    container_name: ansible
    environment: 
      - PUID=1000
      - PGID=1000
    networks:
      - default
    restart: unless-stopped
    env_file: ./.env
    tty: true
    volumes: 
      - /home/nick/Repositories/docker-compose-projects/Ansible/hosts:/ansible/hosts
      - /home/nick/Repositories/docker-compose-projects/Ansible/.ssh:/ansible/.ssh
      - /home/nick/Repositories/docker-compose-projects/Ansible/playbook:/ansible/playbook

